name: "Exemple de workflow - Custom action docker"
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Exécuter l'action Docker
      uses: ./my-custom-action-docker/action.yml
      with:
        message: "Salut de l'action Docker"