name: "Exemple de workflow - Custom Action JS"
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Dire bonjour
      uses: ./my-custom-action-js/action.yml
      with:
        username: "Jean"
        greeting: "Salut"